# frozen_string_literal: true

require_relative '../lib/sales_tax_calculator'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.

RSpec.configure do |config|
  # rspec-expectations config goes here
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Filter lines from Rails gems in backtraces.
  config.filter_gems_from_backtrace

  # Use the documentation formatter for detailed output
  config.default_formatter = 'doc' if config.files_to_run.one?

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option
  Kernel.srand config.seed

  # Allow filtering examples by :focus metadata
  config.filter_run_when_matching :focus

  # Print the 10 slowest examples and example groups
  config.profile_examples = 10

  # Disable monkey patching
  config.disable_monkey_patching!

  # Use expect syntax instead of should
  config.expect_with :rspec do |c|
    c.syntax = :expect
  end
end
